name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/bsmachot-plus
            /usr/bin/git pull origin main
            cp -r /var/www/bsmachot-plus/website/* /www/wwwroot/bsmachot-plus.more30.com/
            echo "Deploy done!"
